org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8

# Enable AndroidX
android.useAndroidX = true
# Enable Jetifier to migrate third-party libraries to AndroidX
android.enableJetifier = true

# Use transitive R class for backward compatibility with old code
android.nonTransitiveRClass=false

# Turn off the full mode of R8 to prevent the reflection code from being overly optimized
android.enableR8.fullMode=false